cloudant/swift-cloudant

Source/CouchDatabaseOperation.swift, Source/CouchOperation.swift, Source/QueryViewOperation.swift, SwiftCloudant.xcodeproj/project.pbxproj, Tests/PutDocumentTests.swift, Tests/QueryViewTests.swift, Tests/TestHelpers.swift
*What*
Added support for querying a view
*How*
Added `QueryViewOperation` accepting properties for optional `queryViewCompletionHandler` and `rowHandler` for processing view results as well as properties for the request query options.
*Testing*
New test cases for querying a view and validation of operation.
reviewer @rhyshort 
reviewer @brynh
=> 34 view query op

Source/CreateDatabaseOperation.swift, Source/DeleteDatabaseOperation.swift, Source/GetDocumentOperation.swift, Source/PutDocumentOperation.swift
Move away from using Error objects such as `.GetDocumentFailed` to using `.HTTP` error instead.
No new testing.
reviewer @ricellis
=> Use HTTP Error for HTTP Errors such as 4xx and 5xx

Source/CouchOperation.swift, Source/QueryViewOperation.swift
Part of #43 
Remove values from Errors enum which are no longer required, and move QueryViewOperation to using `.HTTP` error.
reviewer: @brynh
=> Remove unused errors

Source/CouchOperation.swift, Source/CreateDatabaseOperation.swift, Source/Database.swift, Source/DeleteDatabaseOperation.swift, Source/DeleteDocumentOperation.swift, Source/GetDocumentOperation.swift, Source/PutDocumentOperation.swift, Source/QueryViewOperation.swift, Source/RequestBuilder.swift, Source/RequestExecutor.swift, Source/URLSession.swift, Tests/CreateDatabaseTests.swift, Tests/DeleteDocumentTests.swift, Tests/GetDocumentTests.swift, Tests/PutDocumentTests.swift, Tests/TestHelpers.swift
Change the completion handler signatures to be of type `((response:[String:AnyObject]?, httpInfo:HttpInfo?,error:ErrorProtocol?) -> Void)?`
- Change completion handler signature across all operations.
- Changes the HTTPOperation protocol to pass in `HttpInfo` instead of `statusCode`
No new testing, all tests have been updated to reflect the completion handler changes however.
reviewer @ricellis 
Part of #43
=> Change completion handler signatures

Source/CouchOperation.swift, Source/CreateDatabaseOperation.swift, Source/Database.swift, Source/DeleteDatabaseOperation.swift, Source/DeleteDocumentOperation.swift, Source/GetDocumentOperation.swift, Source/PutDocumentOperation.swift, Source/QueryViewOperation.swift, Tests/CreateDatabaseTests.swift, Tests/DeleteDocumentTests.swift, Tests/GetDocumentTests.swift, Tests/PutDocumentTests.swift, Tests/QueryViewTests.swift, Tests/TestHelpers.swift
Make completionHandlers and processResponses functions common.
- Move `completionHandlers` properties to a single `completionHandler` property on `CouchOperation`
- Make the subclasses `processResponse` function common, and provide implementation in `CouchOperation`, this does not apply to view operations yet since that will require and additional hook to provide row handling.
reveiwer @brynh 
Part of #43
=> Make Completion handlers and processResponse functions common

Source/CouchOperation.swift, Source/QueryViewOperation.swift
Provide a hook into `CouchOperation` to make it possible to call additional completion handlers without reimplementing response processing logic.
Added a new hook into CouchOperation processResponse(json: [String:AnyObkect]) to enable
running of additional completion handlers.
Part of #43
=> Provide hook for executing additional handlers

Source/RequestBuilder.swift, Source/RequestExecutor.swift
Don't crash if RequestBuilder fails to generate a URL for the request.
If generating a URL fails, we throw an error instead of aborting, this allows us to call the completionHandler with the error and complete the operation.
=> Don't crash if URL generation fails.

Source/CouchOperation.swift, Source/QueryViewOperation.swift, Tests/QueryViewTests.swift
Make it possible for operations to complete the operation with error when data serialisation fails
Added new `serialise` hook which is a throwing function which allows operations to error when attempting to transform the data to json.
=> Add hook for data seralisation

Source/CouchOperation.swift, Source/CreateDatabaseOperation.swift, Source/DeleteDatabaseOperation.swift, Source/DeleteDocumentOperation.swift, Source/GetDocumentOperation.swift, Source/PutDocumentOperation.swift, Source/QueryViewOperation.swift
Move callCompletionHandler implementation to CouchOperation.
Now that completionHandlers are common, there is no need for each operation to override the implementation on CouchOperation.
=> Move callCompletionHandler implementation to CouchOperation

CHANGELOG.md, Source/FindDocumentsOperation.swift, SwiftCloudant.xcodeproj/project.pbxproj, Tests/FindDocumentOperationTests.swift
Support Querying for documents using the `_find` endpoint.
- Created FindDocumentsOperation which represents an operation to find documents using the `_find` endpoint.
New test case added: FindDocumentsOperationTests, this contains the following:
- Extensive testing against a Mocked HTTP response using `OHHTTPStubs` 
- Tests to make sure properties return values expected, eg `POST` for HTTP method the body being sent is correct etc.
reviewer @ricellis
Fixes #8
=> Implement Querying for Documents

README.md, Source/PutAttachmentOperation.swift, SwiftCloudant.xcodeproj/project.pbxproj, Tests/PutAttachmentTests.swift
Add the ability to create attachments for a document on the remote server.
Created PutAttachmentOperation which contains the functionality to upload attachments to the server.
reviewer @ricellis
Fixes #63
=> Add Operation to create attachments

Source/DeleteQueryIndexOperation.swift, SwiftCloudant.xcodeproj/project.pbxproj, Tests/DeleteQueryIndexTests.swift
Add the ability to delete query indexes
- Created new DeleteQueryIndexOperation
- Created IndexType enum to provide type safety around index types.
- Tests added to DeleteQueryIndexOperation
reviewer: @brynh
Fixes #9
=> Add DeleteQueryIndexOperation to delete indexes

Source/CreateQueryIndexOperation.swift, Source/FindDocumentsOperation.swift, SwiftCloudant.xcodeproj/project.pbxproj, Tests/CreateQueryIndexTests.swift
Add the ability to create Query indexes.
- CreateJSONIndexOperation to create a JSON index.
- CreateTextIndexOperation to create a text index.
- Created internal protocol `MangoOperation`
- Refactored the `transform` method from `FindDocumentsOperation` into a protocol extension for `MangoOperation`, this provides the transformation methods to only the operations which interact with Mango / Query. 
This is split into two operations instead of one to make it possible to
have compile time type checking for the `fields` parameter. This makes it
more swift like with type safety.
Tests added to CreateQueryIndexTests which test each operation, it uses stubs for the http requests so we can run against CouchDB 1.6.x.
reviewer: @brynh
Resolves #7
=> Add ability to create Query (Mango) Indexes.

CHANGELOG.md, Source/AttachmentOperation.swift, Source/DeleteAttachmentOperation.swift, Source/PutAttachmentOperation.swift, SwiftCloudant.xcodeproj/project.pbxproj, Tests/DeleteAttachmentTests.swift
Add DeleteAttachmentOperation.
Added DeleteAttachmentOperation, the properties required for this is a subset of
PutAttachmentOperation, so DeleteAttachmentOperation becomes the super class for
PutAttachment adding the needed properties.
New tests added to DeleteAttachmentTests
reviewer: @brynh
Fixes #65
=> Add DeleteAttachmentOperation

Source/CouchOperation.swift, Source/RequestExecutor.swift, Source/SessionCookieInterceptor.swift, Source/URLSession.swift
To make it easier to support streaming of data from the server, we need to move
to using delegates so we can dispatch the data back to the requesting operation
as it becomes avaiable. 
URLSessionTask is now just a wrapper for a NSURLSessionDataTask, said task may be swapped out depending on the result of the response interceptor run when the response is reccieved.
In the even the response is reccived from the server and the interceptor run
indicates the request should be retired, the task will be cancelled, and removed
from the taskDict and URLSessionTask, and replaced with a new task which represents
the rerun. Assuming the interceptor run allows for the response to be delivered, the
resposne and data will be deliver to the requesting operation via the InterableSessionDelegate,
this …
=> Move to using delegates to enable streaming support

Source/FindDocumentsOperation.swift, Source/ReadAttachmentOperation.swift, SwiftCloudant.xcodeproj/project.pbxproj, Tests/ReadAttachmentTests.swift
Add the ability to read attachments from the database.
Added the `ReadAttachmentOperation`, this has a couple of limitations,
due to the object hierarchy, the ReadAttachmentOperation defines a new completion handler,
readAttachmentCompletionHandler, to receive the data from the database. This does mean the standard
completion handler *will* not be called for ReadAttachmentOperation instances.
New tests added, see `ReadAttachmentTests` for details.
Resolves #64
=> Add ability to read attachments from the database.

Source/CreateDatabaseOperation.swift, Source/CreateQueryIndexOperation.swift, Source/DeleteAttachmentOperation.swift, Source/DeleteDatabaseOperation.swift, Source/DeleteDocumentOperation.swift, Source/DeleteQueryIndexOperation.swift, Source/FindDocumentsOperation.swift, Source/GetAllDatabasesOperation.swift, Source/GetDocumentOperation.swift, Source/PutAttachmentOperation.swift, Source/PutDocumentOperation.swift, Source/QueryViewOperation.swift, Source/ReadAttachmentOperation.swift, Source/RequestExecutor.swift
Correct the access control specifiers for init methods and `HttpInfo`
- Create public init methods for operations
- Make properties on HttpInfo public.
None, test code isn't effected due to the `@testable` attribute for the imports.
#86 
#87
=> Correct Access control specifiers

Source/CreateDatabaseOperation.swift, Source/CreateQueryIndexOperation.swift, Source/DeleteAttachmentOperation.swift, Source/DeleteDatabaseOperation.swift, Source/DeleteDocumentOperation.swift, Source/DeleteQueryIndexOperation.swift, Source/FindDocumentsOperation.swift, Source/GetAllDatabasesOperation.swift, Source/GetDocumentOperation.swift, Source/Operation.swift, Source/OperationProtocols.swift, Source/PutAttachmentOperation.swift, Source/PutDocumentOperation.swift, Source/QueryViewOperation.swift, Source/ReadAttachmentOperation.swift, Source/RequestBuilder.swift, Source/RequestExecutor.swift, Tests/SwiftCloudant/TestHelpers.swift
Rename `HttpInfo` to `HTTPInfo`
Rename `HttpInfo` to `HTTPInfo`
Making the `HTTP` upper case in `HTTPInfo` makes it more in keeping with the swift API guidelines  
#73
=> Rename HttpInfo to HTTPInfo

Source/CouchClient.swift, Source/CreateQueryIndexOperation.swift, Source/FindDocumentsOperation.swift, Source/Operation.swift, Source/OperationProtocols.swift, Source/PutAttachmentOperation.swift, Source/PutDocumentOperation.swift, Source/QueryViewOperation.swift, Source/ReadAttachmentOperation.swift, Source/RequestBuilder.swift, Source/RequestExecutor.swift, Source/SessionCookieInterceptor.swift, Source/URLSession.swift, Tests/SwiftCloudant/CreateDatabaseTests.swift, Tests/SwiftCloudant/CreateQueryIndexTests.swift, Tests/SwiftCloudant/DeleteAttachmentTests.swift, Tests/SwiftCloudant/DeleteDocumentTests.swift, Tests/SwiftCloudant/DeleteQueryIndexTests.swift, Tests/SwiftCloudant/FindDocumentOperationTests.swift, Tests/SwiftCloudant/GetAllDatabasesTests.swift, Tests/SwiftCloudant/GetDocumentTests.swift, Tests/SwiftCloudant/InterceptorTests.swift, Tests/SwiftCloudant/PutAttachmentTests.swift, Tests/SwiftCloudant/PutDocumentTests.swift, Tests/SwiftCloudant/QueryViewTests.swift, Tests/SwiftCloudant/ReadAttachmentTests.swift, Tests/SwiftCloudant/TestHelpers.swift
Support for the 2016-06-30 Swift 3 Snapshot
- Remove NS Prefixes from some classes, converting them to value types.
- Use modern Dispatch
- This changes means we need to wait forever for the cookie task to complete before continuing.
Tests also updated, they currently all pass
Fixes #83 
Fixes #82
=> Support for the 2016-06-30 Swift 3 Snapshot

Source/FindDocumentsOperation.swift
Correct access level for `Sort` struct members, it should be directly defined as `public` rather than have
no access modifier.
Fixes #98
=> Correct access level for `Sort` struct members

CHANGELOG.md, Source/GetAllDocsOperation.swift, Source/QueryViewOperation.swift, Source/ViewLikeOperation.swift, Tests/SwiftCloudant/GetAllDocsTest.swift, Tests/SwiftCloudant/QueryViewTests.swift
Added support for the `_all_docs` endpoint.
- Create ViewOperation protocol to provide a place to implement common function between `_all_docs` and views.
- Added missing parameters to `QueryViewOperation` so it could conform to the ViewOperation protocol.
- Changed `limit` and `skip` to `UInt` since there is no value in allowing negative integers for these parameters.
- Moved `Stale` enum to outside of `QueryViewOperation` so it can be used with both `_all_docs` and `_view` endpoints. 
New tests added in the AllDocsTests.swift.
Resolves #89
=> Create AllDocs operation

Source/BulkDocs.swift, Tests/SwiftCloudant/BulkDocsTests.swift
Support `_bulk_docs`
Created `PutBulkDocsOperation` API.
Several tests, mostly aimed at the data the operation produced , a single test which goes through the whole HTTP stack.
Resolves #88
=> Support `_bulk_docs`

Tests/SwiftCloudantTests/DeleteAttachmentTests.swift
Make sure deleted attachments are really deleted.
Added additional assertions to `testDeleteAttachment` to make sure that the
attachment is really deleted.
Resolves #72
=> Test Deleted Attachments are deleted

Source/CouchClient.swift, Source/URLSession.swift, Tests/SwiftCloudantTests/InterceptableSessionTests.swift, Tests/SwiftCloudantTests/TestHelpers.swift
Add support for optionally backing off when a `429` response is received from the server.
- Use a dispatch queue for processing the responses from the server, not including the data.
- When a `429` is encountered, dispatch with a delay, starting at 250 milliseconds , doubling for each retry. 
- Limit back off retries to `10` the current hard limit for interceptor driven retries.
- Added a required configuration argument to the `CouchDBClient` init method, this sets if the client should back off, and how many times it should attempt to back off.
Tests added to `InterceptableSessionTests`
Resolves #11
=> Optionally back off when 429 is sent by the server

Source/GetChangesOperation.swift, Tests/SwiftCloudantTests/GetChangesTests.swift
Support the Changes feed.
Created new `GetChangesOperation` API. There are some limitations, for example you cannot stream the changes feed from the server. The current only supported option is a one shot request to get the latest changes, this can be combined with the `since` parameter to get on a subset of the changes in future.
Added GetChangesTests which contains tests for checking the HTTP properties and two full requests to CouchDB.
Resolves #26
=> Support the Changes Feed

.travis.yml
Add Linux builds to travis matrix.
- Add `matrix` key to travis file
- Set overall language to `c` since there isn't a swift.
- Allow Linux builds to fail and not effect the build outcome, this allows
linux support to be phased in gradually.
=> Enable swift testing on linux.

CHANGELOG.md, Source/URLSession.swift, Tests/SwiftCloudantTests/InterceptableSessionTests.swift
Correct issue where constant 401 responses from an endpoint would cause an infinite retry loop.
Decrement remainingRetries counter and check that is greater than zero before attempting to 
retry the request.
Added a new test, and modified `CookieSession401` URLProtocol response to contain the `error` key.
Fixes #135
=> Fix issue where 401 response triggers infinite loop.

Source/SwiftCloudant/Operations/Documents/PutDocumentOperation.swift, Tests/SwiftCloudantTests/GetDocumentTests.swift, Tests/SwiftCloudantTests/PutDocumentTests.swift
Made it possible to use the server to generate doc ids.
Loosen the restriction on `PutDocumentOperation` for the `id` parameter,
to allow `nil` to use the sever to generate a doc id when the document
is saved.
Several new tests added to `PutDocumentTests`
Fixes #97
=> Make it possible to use the server to generate doc ids.

Source/SwiftCloudant/HTTP/URLSession.swift, Tests/SwiftCloudantTests/CouchClientTest.swift
Fix crash on deallocate for unused client.
Only call `self.session.finishTasksAndInvalidate()` if the client has received a request. 
Add additional unit test to instantiate an unused client.
=> Fix crash on deallocate for unused client

Source/SwiftCloudant/CouchClient.swift, Tests/SwiftCloudantTests/CouchClientTest.swift
Implement convenience init for creating client from VCAP services environment variable.
Parse a `VCAP_SERVICES` environment variable allowing easy binding of a service instance to a Bluemix application.
Includes additional unit tests.
Fixes #143.
=> Implement convenience init for creating client from VCAP services env

Tests/SwiftCloudantTests/FindDocumentOperationTests.swift
Within the findDocumentOperationTests, a few of the tests were attempting to downcast a result from jsonObject to [String: NSObject] however this was returning nil on Linux which was causing the tests to fail. Changing the casting to [String: Any] fixes this issue and is the change I've made in 4 of the tests. 
Edited the test themselves to the new casting to [String: Any]
Running the findDocumentOperationTests will test these changes, and on Linux they should now pass and still pass on Mac. 
https://github.com/IBM-Swift/SwiftRuntime/issues/284
=> Changed the downcasting from [String:NSObject] to [String:Any]

Source/SwiftCloudant/Operations/Operation.swift
Now that Foundation on Linux support async Operations via KVO APIs, we can remove the Linux-specific code in Cloudant.
=> Use KVO APIs for Operations

Source/SwiftCloudant/Operations/Views/ViewPaging.swift
Fix a warning in the ViewPager class.
Change the access level of `ViewPager.State` to `fileprivate` from `private`
No new tests, all tests pass and warning is not present in xcode 8.3.
Fixes #151
=> Fix Warning with ViewPaging.State.

Source/SwiftCloudant/HTTP/URLSession.swift
As `Bundle(for:)` is not available on Linux, and is unlikely to be implemented in the short-term, work around this omission.
=> Workaround lack of Bundle(for:) on Linux

Tests/SwiftCloudantTests/InterceptableSessionTests.swift, Tests/SwiftCloudantTests/TestHelpers.swift
On Linux, Dispatch must be imported explicitly.  Importing it on Darwin as well does no harm, so just add the `import Dispatch` to those files which use it.
=> Import Dispatch explicitly

Tests/SwiftCloudantTests/BulkDocsTests.swift, Tests/SwiftCloudantTests/CreateQueryIndexTests.swift, Tests/SwiftCloudantTests/FindDocumentOperationTests.swift, Tests/SwiftCloudantTests/GetAllDocsTest.swift, Tests/SwiftCloudantTests/ViewPagingTests.swift
Although Darwin platforms have automatic bridging between Foundation types such as `NSDictionary` and Swift types like `Dictionary`, this is unfortunately not supported on Linux.
Work around this by explicitly bridging instead.  Although this does create additional instances of Foundation classes on Darwin, this is OK as it's only in the tests so won't affect performance.
=> Remove implicit bridging in tests

Source/SwiftCloudant/HTTP/URLSession.swift
Thanks for your hard work, please ensure all items are complete before opening.
/Source/SwiftCloudant/HTTP/URLSession.swift  is performing an explicit cast  from String to NSString as below which does not work on Linux due to which the test suite crashes on linux while processing the ```httpAdditionalHeaders``` by Swift Foundation .
``` config.httpAdditionalHeaders = [("User-Agent" as NSString) as AnyHashable: InterceptableSession.userAgent()]```.
Moreover, we don't need  explicit casting as the String itself   can be casted to AnyHashable .
Removed  explicit casting to NSString
Running the cloudant test-suite on Linux
https://github.com/IBM-Swift/SwiftRuntime/issues/382
=> Crash in Cloudant tests due to httpAdditionalHeaders [382]

.travis.yml, Jenkinsfile, Package.swift, Source/SwiftCloudant/CouchClient.swift, Source/SwiftCloudant/HTTP/URLSession.swift, SwiftCloudant.podspec
Fix incorrect behaviour when fetching version number for user-agent string
`Bundle(for:)` is not supported on Linux
(https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/Bundle.swift), and we don't expect it to be supported any time soon.
Instead, define the version number in CouchDBClient and hardcode the first part of the
user-agent as "SwiftCloudant".
All existing tests pass
Once merged, fix instructions in https://github.com/cloudant/cloudant-sync/blob/master/releasing-swift.md regarding version number updates.
See #170
=> Use CouchDBClient.version for user-agent string

.travis.yml, CHANGELOG.md, Package.swift, SwiftCloudant.podspec
Thanks for your hard work, please ensure all items are complete before opening.
Reverted the Swift version to 3.1
There is no "3.2" tools version for Linux so using 3.2 prevents `swift` CLI commands from executing on that platform (even when using 4.x releases of Swift). Although not everything works on Linux, it is better to have the stuff that works keep working rather than having nothing work with a 3.2 change.
Also updated the Linux Swift download to a more newly released version which allows SwiftCloudant to compile cleanly and the tests to execute (even though the runtime regression that prevents the `GetChanges` tests passing is still present.
Existing macOS tests pass, Linux tests run and the expected ones pass.
N/A
=> Revert to version 3.1

CHANGELOG.md, README.md, Source/SwiftCloudant/CouchClient.swift, SwiftCloudant.podspec
Thanks for your hard work, please ensure all items are complete before opening.
Proposed 0.8.0 release
- [NEW] Runs on Swift 4.x on Linux with some limitations (see note).
- [FIXED] Set the default Swift language version in the SwiftCloudant.podspec to 3.1.
- [FIXED] Fixed warning for non-exhaustive switch statement.
- [NOTE] The `GetChangesOperation` is not currently supported by the Linux platform,
see [issue #176](https://github.com/cloudant/swift-cloudant/issues/176).
N/A - release
https://github.com/cloudant/swift-cloudant/milestone/8
=> Proposed 0.8.0 release

CHANGELOG.md, Source/SwiftCloudant/CouchClient.swift, SwiftCloudant.podspec
Thanks for your hard work, please ensure all items are complete before opening.
Proposed 0.9.0 release
- [UPGRADED] Minimum Swift language version to 4.2.
- [UPGRADED] Swift tools version and package manifest to version 5.0.
- [BREAKING CHANGE] Projects using older Swift tool and language versions will not work with versions newer than 0.8.0.
- [FIXED] Fixed scope of `Operation.Error` to be exposed as public.
N/A - release
https://github.com/cloudant/swift-cloudant/milestone/9
=> Proposed 0.9.0 release
